---
# tasks file for vmware specific validations
- name: Ensure VMware Pyvmomi libraries are installed
  python_requirements_info:
    dependencies:
    - pyvmomi
  register: _py_facts

- name: Fail if Python modules are missing
  fail:
    msg: |
         Missing python module(s) pyvmomi on {{ groups['assisted_installer'][0] }} use 'pip3 install pyvmomi'
  when: _py_facts.not_found | length > 0
  delegate_to: localhost
