---
- name: Mount Live ISO(Dell iDRAC9+ only)
  block:
    - name: DELL Eject Virtual Media (if any)
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaEject
        baseuri: "{{ hostvars[item]['bmc_address'] }}"
        username: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        virtual_media:
          image_url: "{{ webserver }}/{{ iso }}"
        resource_id: iDRAC.Embedded.1
      ignore_errors: yes

    - name: DELL Insert Virtual Media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{ hostvars[item]['bmc_address'] }}"
        username: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        virtual_media:
          image_url: "{{ webserver }}/{{ iso }}"
          media_types:
          - CD
          - DVD
        resource_id: iDRAC.Embedded.1
