---
- name: Mount Live ISO, Boot into Live ISO (HPE servers)
  block:
    - name: HPE disconnect existing Virtual Media
      hpilo_boot:
        host: "{{ bmc_address }}"
        login: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        state: disconnect
      delegate_to: localhost

    - name: HPE task to boot a system using an ISO
      hpilo_boot:
        host: "{{ bmc_address }}"
        login: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        image: "{{ webserver }}/{{ iso }}"
        media: cdrom
        state: connect
      delegate_to: localhost

    - name: Pause for 30 seconds to media being inserted at OS
      pause:
        seconds: 30
