---
- name: Mount Live ISO, Boot into Live ISO (SuperMicro servers)
  block:
    - name: Unmount SuperMicro ISO
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.UnMount"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        headers:
          content-type: application/json
          Accept: application/json
        body: {}
        body_format: json
        validate_certs: no
        force_basic_auth: yes
        return_content: yes

    - name: Patching Host and Path for Mounting ISO
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VM1/CfgCD"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: PATCH
        headers:
          content-type: application/json
          Accept: application/json
        body: "{\"Host\": \"{{ webserver }}\", \"Path\": \"{{ iso }}\"}"
        body_format: json
        force_basic_auth: yes
        validate_certs: no
        return_content: yes

    - name: Mount SuperMicro ISO
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VM1/CfgCD/Actions/IsoConfig.Mount"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        headers:
          content-type: application/json
          Accept: application/json
        body: {}
        body_format: json
        validate_certs: no
        force_basic_auth: yes
        return_content: yes
