galaxy_info:
  author: Pablo Iranzo Gómez
  description: Removes iso from BMC
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.9
  galaxy_tags: []
dependencies: []
